### ISSUE TITLE
Navigation: Add useful Navbar

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#1]
Navigation: As a **user** I can **view a navbar from every page** so that I can **navigate easily between pages**

**Acceptance Criteria**
- [x] Add NavBar
- [x] Add correct criteria

**Tasks**
- [x] Choose correct options to be displayed
- [x] Enter NavBar component
- [x] Make component available to App.js

**Manual Test**
- [x] Test that options are visible correctly on the NavBar
