### ISSUE TITLE
Posts: Like a post

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#10]
Like a post: As a **logged in user** I can **like a post** so that I can **show my support for the posts that interest me**

**Acceptance Criteria**
- [x] Upon being logged in, a user should be able to like a post

**Tasks**
- [x] Create like function, including button
- [x] Connect function to be compatible with posts
- [x] Likes should also be counted when clicked on
- [x] Enable liking function only when logged in

**Manual Tests**
- [x] Firstly log in, then test that the like button is available and can also be clicked on
- [x] Test that like button can also be clicked on again to remove like
