### ISSUE TITLE
Posts: Dislike a post

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#11]
Dislike a post: As a **logged in user** I can **dislike a post** so that I can **show that a post is not liked by me**

**Acceptance Criteria**
- [ ] Upon being logged in, a user should be able to dislike a post

**Tasks**
- [ ] Create like function, including button
- [ ] Connect function to be compatible with posts
- [ ] Dislikes should also be counted when clicked on
- [ ] Enable disliking function only when logged in

**Manual Tests**
- [ ] Firstly log in, then test that the dislike button is available and can also be clicked on
- [ ] Test that dislike button can also be clicked on again to remove the dislike

**Comment by WelshDan** [comment]
This was removed due to time constraints
