### ISSUE TITLE
Posts: Search using keywords

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#14]
Search: As a **user** I can **search for posts with keywords** so that I can **find the posts and user profiles I am most interested in**

**Acceptance Criteria**
- [x] Create a search function that returns posts containing the searched keywords

**Tasks**
- [x] Add search function to feed to be able to search through post and return those that contain the searcg keywords.

**Manual Tests**
- [x] Enter keyword to see if it returns the correct search results
