### ISSUE TITLE
Posts: Add images to posts

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#15]
Add images to posts: As a **user** I can **add a picture to my post** so that I can **show others what has interested me**

**Acceptance Criteria**
- [x] Create the option of adding an image file to posts to enhance user interaction

**Tasks**
- [x] Add media sources as alternative when posting

**Manual Tests**
- [x] Test that an image file can be added to posts by logged in user
- [x] Test that added image is viewable
