### ISSUE TITLE
Posts: View liked posts

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#16]
View liked posts: As a **logged in user** I can **view the posts I liked** so that I can **find the posts I enjoy the most**

**Acceptance Criteria**
- [x] Create a search function to show only the liked posts to be viewed

**Tasks**
- [x] Add search function for liked posts, only when logged in

**Manual Tests**
- [x] Log in, check the search function filters in all posts liked by the user
