### ISSUE TITLE
Posts: User can edit posts

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#18]
Edit post: As a **post owner** I can **edit my post title and description** so that I can **make corrections or update my post after it was created**

**Acceptance Criteria**
- [x] Posts can be edited - both title and description - after it is created by the user

**Tasks**
- [x] Create edit function for user's own post so they can edit after creation

**Manual Tests**
- [x] After logging in, try and edit title and description to a post
