### ISSUE TITLE
Comments: Create a comment

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#19]
Create a comment: As a **logged in user** I can **add comments to a post** so that I can **share my thoughts about the post**

**Acceptance Criteria**
- [x] Create comment function
- [x] Allow logged in user ability to add comment to other user's post

**Tasks**
- [x] For a logged in user, add an add comment function and button
- [x] Allow comment to be added and saved to post
- [x] Username and avatar of the user who comments should be visible alongside comment

**Manual Tests**
- [x] After logging in, add comment button should work
- [x] Leave a comment - it should save to the post
- [x] Check username and avatar of the user who comments is visible alongside comment
