### ISSUE TITLE
Routing: Keep design simple and code as clean as possible

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#2]
Routing: As a **user** I can **navigate through pages quickly** so that I can **view content seamlessly without page refresh**

**Acceptance Criteria**
- [x] Create a simple design
- [x] Write as simple code as possible to keep loading speed down

**Tasks**
- [x] Keep layout simple and concise
- [x] Check that code is optimised to keep loading speed down

**Comment by WelshDan** [comment]
Unfortunately the code is incomplete in many places
