### ISSUE TITLE
Comments: Comment date

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#20]
Comment date: As a **user** I can **see how long ago a comment was made** so that **I know how old a comment is**

**Acceptance Criteria**
- [x] Add date stamp to comments

**Tasks**
- [x] Create a time stamp function connected to when a user leaves a comment - comment will show has long ago a comment was made

**Manual Tests**
- [x] Add a comment and check that the comment has a time stamp
