### ISSUE TITLE
Comments: View a comment

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#21]
View comments: As a **user** I can **read comments on posts** so that I can **read what other users think about the posts**

**Acceptance Criteria**
- [x] Click on comments to read them

**Tasks**
- [x] Make comments available to be viewed by everyone

**Manual Tests**
- [x] Test to see if comments can be read both when logged in and logged out
