### ISSUE TITLE
Comments: Delete a comment

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#22]
Delete comments: As an **owner of a comment** I can **delete my comment** so that I can **control removal of my comment from the application**

**Acceptance Criteria**
- [x] Comments should be deletable by the owner and only the owner

**Tasks**
- [x] Add a delete comment button that delete comments on pressing

**Manual Tests**
- [x] Test that comments can be deleted when user is logged in
- [x] Test that comments cannot be deleted when user is logged out
