### ISSUE TITLE
Comments: Edit a comment

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#23]
Edit a comment: As an **owner of a comment** I can **edit my comment** so that I can **fix or update my existing comment**

**Acceptance Criteria**
- [x] Create an edit button that then enables user to be able to edit their own comments and not comments others have left
- [x] Updated comments should then be saved and replaced previous comment

**Tasks**
- [x] Create edit button
- [x] When logged in, edit button should be available only on own comments
- [x] Updated comments should replace previous comments

**Manual Tests**
- [x] Test edit button is available when logged in
- [x] Test comment becomes editable on clicking edit button
- [x] Test edited comment saves
- [x] Test edited comment is viewable and not previous comment
