### ISSUE TITLE
Profile: View other's profiles

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#25]
Profile page: As a **user** I can **view other users profiles** so that I can **see their posts and learn more about them**

**Acceptance Criteria**
- [x] Create profile page
- [x] Make profile page viewable to others who click on username

**Tasks**
- [x] Create user profile including basic user information
- [x] Enable profile to be viewed to user who are logged in before clicking on user

**Manual Tests**
- [x] Test user profile opens
- [x] Test user profile can save the information
- [x] Test user profile can be viewed by other users who are logged in and click on the user's username
- [x] Test to make sure the user profile is not available when a user is not logged in
