### ISSUE TITLE
Profile: User stats

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#27]
User profile - user stats: As a **user** I can **view statistics about a specific user: bio, number of posts, follows and users followed** so that I can **learn more about them**

**Acceptance Criteria**
- [x] Add user statistics to profile page
- [x] Make sure they are viewable to a logged in user

**Tasks**
- [x] Link statistics to profile page

**Manual Tests**
- [x] Test user stats are shown on user profile
- [x] Test that they add up correctly
