### ISSUE TITLE
Feed: Link/unlink teams

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#28]
Link/Unlink a team: As a **logged in user** I can **link and unlink to teams** so that I can **see, like and comment on posts linked to that team**

**Acceptance Criteria**
- [ ] Create a searchable list of teams to be linkable to user's feed
- [ ] Only posts about these linked teams will be showed in the linked feed

**Tasks**
- [x] Add linkable teams list to user's feed page
- [x] Upon choosing a linked team, posts about that linked team should then be viewable in the linked feed
- [x] This should only be viewable when a user is logged in

**Manual Tests**
- [x] Test that the linkable teams list is viewable in user's feed page
- [ ] Test that linkable teams show in the linked feed
- [ ] Test that this only works when a user is logged in and does not work when logged out

**Comment by WelshDan** [comment]
Not used due to time constraints
