### ISSUE TITLE
Feed: Follow/unfollow a user

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#29]
Follow/Unfollow a user: As a **logged in user** I can **follow and unfollow other users** so that I can **see and remove posts by specific users in my posts feed**

**Acceptance Criteria**
- [x] Create a follow/unfollow button to only show on other user's profiles
- [x] On clicking the button, user should then be able to follow the other user's posts/actions and also show that they are being followed

**Tasks**
- [x] Add clickable follow/unfollow button
- [x] Followed user should then have posts viewable in feed
- [x] On unfollowing, then the user should have followed posts removed from feed

**Manual Tests**
- [x] Test that the followed user's posts are viewable in user's feed page
- [x] Test that followed people's posts show in the feed page
- [x] Test that this function is removed when a followed user is unfollowed
- [x] Test that this only works when a user is logged in and does not work when logged out
