### ISSUE TITLE
Authentication: Sign up function

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#3]
Authentication - Sign up: As a **user** I can **create a new account** so that I can **access all the features for signed up users**

**Acceptance Criteria**
- [x] Create sign up function to app
- [x] Choose an outlook that is pleasing and complies with style and colour code
- [x] New users information shall be stored
- [x] Test that function works

**Tasks**
- [x] Choose a design that is suitable
- [x] Add sign up component
- [x] Entered information shall be stored
- [x] As a signed in user then different NavBar options shall be available

**Manual Test**
- [x] Sign up as a new user
- [x] Sign in using those new user details
- [x] Check the user functions are available in the NavBar
