### ISSUE TITLE
Posts: View posts by specific user

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#30]
View all posts by a specific user: As a **user** I can **view all the posts by a specific user** so that I can **catch up on their latest posts, or decide I want to follow them**

**Acceptance Criteria**
- [x] Other user's posts can be viewable by clicking on their profile, then clicking on their posts
- [x] This should only be available to users who are logged in

**Tasks**
- [x] Create view posts button on a user's profile page
- [x] User A should then be able to go in and see all of User B's posts
- [x] This option is only available when logged in

**Manual Tests**
- [x] Add view posts button to user profiles (says view my posts on own profile)
- [x] Test that users can view other user's posts
- [x] Test that this is only avilable when logged in and NOT available when logged out
