### ISSUE TITLE
Profile: Edit profile

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#31]
Edit profile: As a **logged in user** I can **edit my profile** so that I can **change my profile picture, country of residence, age, favourite team and bio**

**Acceptance Criteria**
- [ ] Create an editable function to the profile page
- [ ] This should only be available when logged in and only one's own profile can be changed

**Tasks**
- [x] Add edit profile button
- [x] Upon clicking, the option to edit all information on the profile should be available
- [ ] Updated information should be shown on the user's profile

**Manual Tests**
- [x] Test the edit profile button opens up the option to change profile information
- [x] Test that information can be changed
- [x] Test that information is stored on saving
- [x] Test that this is only available when logged in
- [x] Test that this information can only be changed on one's own profile page
- [x] Test that the edit profile button is not available when user is not logged in

**Comment by Ahcai2006** [comment]
> Edit profile: As a **logged in user** I can **edit my profile** so that I can **change my profile picture, country of residence, age, favourite team and bio**
> 
> **Acceptance Criteria**
> - [ ] Create an editable function to the profile page
> - [ ] This should only be available when logged in and only one's own profile can be changed
> 
> **Tasks**
> - [ ] Add edit profile button
> - [ ] Upon clicking, the option to edit all information on the profile should be available
> - [ ] Updated information should be shown on the user's profile
> 
> **Manual Tests**
> - [ ] Test the edit profile button opens up the option to change profile information
> - [ ] Test that information can be changed
> - [ ] Test that information is stored on saving
> - [ ] Test that this is only available when logged in
> - [ ] Test that this information can only be changed on one's own profile page
> - [ ] Test that the edit profile button is not available when user is not logged in

**Comment by Ahcai2006** [comment]
> Edit profile: As a **logged in user** I can **edit my profile** so that I can **change my profile picture, country of residence, age, favourite team and bio**
> 
> **Acceptance Criteria**
> - [ ] Create an editable function to the profile page
> - [ ] This should only be available when logged in and only one's own profile can be changed
> 
> **Tasks**
> - [ ] Add edit profile button
> - [ ] Upon clicking, the option to edit all information on the profile should be available
> - [ ] Updated information should be shown on the user's profile
> 
> **Manual Tests**
> - [ ] Test the edit profile button opens up the option to change profile information
> - [ ] Test that information can be changed
> - [ ] Test that information is stored on saving
> - [ ] Test that this is only available when logged in
> - [ ] Test that this information can only be changed on one's own profile page
> - [ ] Test that the edit profile button is not available when user is not logged in
