### ISSUE TITLE
Profile: Edit personal details

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#32]
Update username and password: As a **logged in user** I can **update my username and password** so that I can **change my display name and keep my profile secure**

**Acceptance Criteria**
- [x] Create an update profile details button
- [x] This option should not be available when not logged in and not available for other users to change.

**Tasks**
- [x] Add a personal information page
- [x] Add an edit profile information button
- [x] On clicking button, profile information should be able to be updated
- [x] The new information is saved on the user's profile information page

**Manual Tests**
- [x] Test a logged in user can access the profile information page
- [x] Test that the update personal information button works and upon clicking presents the option to update information
- [x] Test that information is saved
- [x] Test that this option is not available to users who are not logged in
