### ISSUE TITLE
Posts: Add videos to posts

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#33]
Add video to posts: As a **user** I can **add a video file to my post** so that I can **show others what has interested me**

**Acceptance Criteria**
- [ ] Create the option of adding a video file to posts to enhance user interaction

**Tasks**
- [ ] Add video source as alternative when posting

**Manual Tests**
- [ ] Test that a video file can be added to posts by logged in user
- [ ] Test that video files uploads and can be played

**Comment by WelshDan** [comment]
This was removed due to time constraints
