### ISSUE TITLE
Authentication: Sign in function

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#4]
Authentication - Sign in: As a **user** I can **sign in to the app** so that I can **access functionality for logged in users**

**Acceptance Criteria**
- [x] Upon signing in, user functions shall become available - viewable on NavBar
- [x] Profile page can be accessed and changed
- [x] User can create, edit and delete own posts
- [x] User can like other posts
- [x] Upon logging out, user functions are now hidden

**Tasks**
- [x] Create authentication for signing in users in user functions components for posts, likes and profile

**Manual Test**
- [x] Sign in
- [x] See user options in NavBar
- [x] Upon sign out, the sign in icon is shown and functions are now blocked
