### ISSUE TITLE
Authentication: Access tokens

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#5]
Authentication - Refreshing access tokens: As a **user** I can **maintain my logged-in status until I choose to log out** so that **my user experience is not compromised**

**Acceptance Criteria**
- [x] Once logged in, a logged in status shall be maintained even after clicking on one or multiple pages
- [x] User shall not be logged out until the log out function is activated

**Tasks**
- [x] Logged in user status is held despite activity

**Manual Test**
- [x] Log in
- [x] Click on every page and every function and check that the logged in status is maintained
