### ISSUE TITLE
Navigation: Sign in, Sign up functions visible

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#6]
Navigation: Conditional rendering - As a **logged out user** I can **see sign in and sign up options** so that I can **sign in/sign up**

**Acceptance Criteria**
- [x] Add Sign in function to NavBar
- [x] Add Sign up function to NavBar

**Tasks**
- [x] Add Sign in and Sign up choices to NavBar
- [x] Create clickable function for both

**Manual Test**
- [x] Test that Sign in can be clicked on
- [x] Test that Sign up can be clicked on
