### ISSUE TITLE
Avatar: Enable avatar usage

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#7]
Avatar: As a **user** I can **view user's avatars or profile pics** so that I can **easily identify users of the application**

**Acceptance Criteria**
- [x] Enable avatar use ready for profile pages/user interactions

**Tasks**
- [x] Create avatar component
- [x] Connect to app and enable its functionality

**Manual Tests**
- [x] Check that avatar images can be added to profile
- [x] Check that avatar images are visible when user posts
- [x] Check that avatar images can be changed/updated in the user's profile page
