### ISSUE TITLE
Posts: Create a post

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#8]
Create posts: As a **logged in user** I can **create posts** so that I can **share my views**

**Acceptance Criteria**
- [x] Add a create posts function
- [x] Enable user can attach their own words to the post
- [x] Enable user to be able to send post to be visible in the feed

**Tasks**
- [x] Attach button to function
- [x] Create posts function
- [x] Attach posts function to App.js
- [x] Post is to be added to feed - shown in order by time posted

**Manual Tests**
- [x] Click on button to create post
- [x] Attach posts function to App.js
- [x] Check post is visible in feed
- [x] Check user's name and avatar is shown next to post
- [ ] Check team link is correct

**Comment by WelshDan** [comment]
Link function not created in time
