### ISSUE TITLE
Posts: View a post

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/fanzone-frontend#9]
View a post: As a **user** I can **view the details of a single post** so that I can **learn more about it**

**Acceptance Criteria**
- [x] Click on post to view

**Tasks**
- [x] Click on post and make sure it is viewable and poster's details are also visible
- [x] User options SHOULD NOT be accessible when user is not logged in

**Manual Test**
- [x] WHEN NOT LOGGED IN: Check post is ok and that poster's avatar and name are visible
- [x] WHEN NOT LOGGED IN: Check user options are not available
- [x] WHEN LOGGED IN: Check post is ok and that poster's avatar and name are visible
- [x] WHEN LOGGED IN: Check that user options are available
